name: Plan changes

on:
  pull_request:
    branches:
      - main
    paths:
      - terraform/*

permissions:
      id-token: write
      contents: read

env:
  AWS_REGION : "eu-west-1"

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          working_directory: ""
          tfsec_formats: sarif
          tfsec_args: --concise-output --no-ignores --force-all-dirs --minimum-severity HIGH
          github_token: ${{ secrets.TFSEC_GITHUB_TOKEN }}

  plan:
    name: Pull Request Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::034421805275:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: Terraform plan
        run: |
          terraform init -input=false 
          terraform plan -input=false

      - name: Terraform apply
        run: |-
          terraform init -input=false 
          terraform apply --auto-approve
          terraform output