name: Plan changes

on:
  push:
    branches: 
      - wip
  pull_request:
    branches:
      - wip
    paths:
      - terraform/*

permissions:
      id-token: write
      contents: read

env:
  AWS_REGION : <"us-east-1"> 

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          working_directory: ""
          tfsec_formats: sarif
          tfsec_args: --concise-output --no-ignores --force-all-dirs--minimum-severity HIGH
          github_token: ${{ secrets.GITHUB_TOKEN }}

  plan:
    name: Pull Request Plan
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup terraform/terragrunt tools
        uses: cds-snc/terraform-tools-setup@v1
        env:
          TERRAFORM_VERSION: 1.5.3
          TERRAGRUNT_VERSION: 0.45.10

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::034421805275:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      # - name: Terragrunt plan
      #   uses: cds-snc/terraform-plan@v3
      #   with:
      #     comment-delete: true
      #     terragrunt: true
      #     skip-conftest: true
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"